language: objective-c
osx_image: xcode8.2

env:
   global:
   - LANG=en_US.UTF-8

   - PROJECT="SwipeCellKit.xcodeproj"
   - IOS_SCHEME="SwipeCellKit"
   - IOS_SDK=iphonesimulator10.2  

   matrix:
   - DESTINATION="OS=10.0,name=iPhone 6s" SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" BUILD_EXAMPLE="YES" POD_LINT="YES"
   - DESTINATION="OS=10.1,name=iPhone 7"  SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" BUILD_EXAMPLE="YES" POD_LINT="NO"
   - DESTINATION="OS=10.2,name=iPad Pro (9.7 inch)"  SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" BUILD_EXAMPLE="YES" POD_LINT="NO"

script:
- set -o pipefail

- if [ $POD_LINT == "YES" ]; then
      pod lib lint;
  fi


- if [ $BUILD_EXAMPLE == "YES" ]; then
      xcodebuild build analyze -project Example/MailExample.xcodeproj -scheme MailExample -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty -c;
  fi